### ISSUE TITLE
Flurry of slowness and problems in colab.

### ISSUE THREAD

**Issue by killporter** [11cafe/comfyui-workspace-manager#86] opened 2024-01-08 13:31 UTC
Running this in a colab enviroment, almost every time i try to add to queue the adding it to the queue tends to take from 10 second to minutes, and my logs become a flurry of:
ConnectionResetError: Connection lost
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/content/drive/MyDrive/ComfyUI/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-workspace-manager.disable/__init__.py", line 143, in save_db
    data = await request.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_request.py", line 684, in json
    body = await self.text()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_request.py", line 678, in text
    bytes_body = await self.read()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_request.py", line 663, in read
    chunk = await self._payload.readany()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 395, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 302, in _wait
  
  the time to load the ui itself takes longer as well, any workflow i try

**Comment by Weixuanf** [comment] 2024-01-08 13:56
Ok Im thinking if this is due to the auto save 🤔

what if you just add this one line of code here:
<img width="625" alt="Screenshot 2024-01-08 at 9 54 12 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/9d5aee21-7303-4666-bb94-7760f6c7306b">
In `/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py`
```
@server.PromptServer.instance.routes.post("/workspace/save_db")
async def save_db(request):
    return web.Response(text=f"Return early to debug") // Add this one line
```

and restart your python server, will it become better?

**Comment by Weixuanf** [comment] 2024-01-08 14:02
what workflow were you using? like animatediff, svd or other stuff. yesterday i did try a bit with the most default flow text to image, it was working ok. I got kicked out of the cloud GPU and couldn't debug anymore. I'll try again today

**Comment by Weixuanf** [comment] 2024-01-11 13:53
Hi I have been debugging this for a while. This is caused by the bundle size of our app (larger than pure js app since we’re using react) and how we’re storing out db now.

to solve this issue, I’m planning to:
1) migrate to indexdb so there won’t be so many network requests to server
2) enable dynamic chunk loading in react

it’s gonna take some time to fix this issue. I’ll update here once it’s done.

**Comment by Weixuanf** [comment] 2024-02-01 13:39
hi this should be fixed in our latest version, please upgrade and see if it works for you

**Closed** 2024-02-07 14:37 UTC
